### ISSUE TITLE
Reactアプリの雛形を作る

### ISSUE THREAD

**Issue by HiroshiNakamura** [siida36/spa-boot-camp#2]
みんなで読んだハンズオンを参考にする
https://qiita.com/TsutomuNakamura/items/72d8cf9f07a5a30be048

またはcreate-react-appを使う

どちらで作っても最初以外はあまり変わらないはず

**Comment by ghost** [comment]
TODO
- 元あったファイルの回復
- npm install などの手順を README.md に追記

**Comment by HiroshiNakamura** [comment]
#20で対応
